spring.application.name=argos

# Configuração para fase de desenvolvimento (com H2 em memória)
# Quando estiver pronto para usar Oracle, altere para as credenciais reais
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# H2 Console para debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger/Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
spring.jackson.serialization.fail-on-empty-beans=false



# Server
server.port=8080

