spring.application.name=argos

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
spring.datasource.username=RM559885
spring.datasource.password=180506

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Swagger/Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
spring.jackson.serialization.fail-on-empty-beans=false

# Server
server.port=8080

# Connection pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# JWT Configuration
jwt.secret=minha-chave-secreta-super-segura-para-o-projeto-argos-2024-2025
jwt.expiration=86400000

