-- ============================================================
-- PROJETO ARGOS — DDL Oracle SQL
-- ============================================================

-- ── SEQUÊNCIAS ───────────────────────────────────────────────

CREATE SEQUENCE SEQ_MISSAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_LEITURA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ALERTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ── TABELAS ──────────────────────────────────────────────────

CREATE TABLE TB_MISSAO (
    ID_MISSAO        NUMBER(19)      NOT NULL,
    NM_MISSAO        VARCHAR2(100)   NOT NULL,
    DS_MISSAO        VARCHAR2(500)   NOT NULL,
    TP_STATUS        VARCHAR2(20)    NOT NULL,
    TP_RISCO         VARCHAR2(10)    NOT NULL,
    DS_AREA          VARCHAR2(150)   NOT NULL,
    DT_CRIACAO       TIMESTAMP       NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_MISSAO PRIMARY KEY (ID_MISSAO),
    CONSTRAINT CK_STATUS CHECK (TP_STATUS IN ('PLANEJADA', 'ATIVA', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT CK_RISCO  CHECK (TP_RISCO  IN ('BAIXO', 'MEDIO', 'ALTO', 'CRITICO'))
);

CREATE TABLE TB_LEITURA_SENSOR (
    ID_LEITURA   NUMBER(19)    NOT NULL,
    ID_MISSAO    NUMBER(19)    NOT NULL,
    TP_SENSOR    VARCHAR2(20)  NOT NULL,
    VL_LEITURA   NUMBER(10,4)  NOT NULL,
    DS_UNIDADE   VARCHAR2(20)  NOT NULL,
    DT_LEITURA   TIMESTAMP     NOT NULL,
    FL_ANOMALIA  NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_LEITURA      PRIMARY KEY (ID_LEITURA),
    CONSTRAINT FK_LEITURA_MISSAO FOREIGN KEY (ID_MISSAO) REFERENCES TB_MISSAO(ID_MISSAO),
    CONSTRAINT CK_SENSOR       CHECK (TP_SENSOR IN ('TEMPERATURA', 'PRESSAO', 'VIBRACAO', 'COMBUSTIVEL', 'SINAL')),
    CONSTRAINT CK_ANOMALIA     CHECK (FL_ANOMALIA IN (0, 1))
);

CREATE TABLE TB_ALERTA (
    ID_ALERTA      NUMBER(19)    NOT NULL,
    ID_MISSAO      NUMBER(19)    NOT NULL,
    DS_MENSAGEM    VARCHAR2(300) NOT NULL,
    TP_SEVERIDADE  VARCHAR2(10)  NOT NULL,
    FL_RESOLVIDO   NUMBER(1)     DEFAULT 0 NOT NULL,
    DT_ALERTA      TIMESTAMP     NOT NULL,
    CONSTRAINT PK_ALERTA         PRIMARY KEY (ID_ALERTA),
    CONSTRAINT FK_ALERTA_MISSAO  FOREIGN KEY (ID_MISSAO) REFERENCES TB_MISSAO(ID_MISSAO),
    CONSTRAINT CK_SEVERIDADE     CHECK (TP_SEVERIDADE IN ('INFO', 'AVISO', 'CRITICO')),
    CONSTRAINT CK_RESOLVIDO      CHECK (FL_RESOLVIDO IN (0, 1))
);